flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.6.0.0
- HTTP-4000.3.6
- MonadPrompt-1.0.0.5
- MonadRandom-0.5.1
- QuickCheck-2.9.2
- ReadArgs-1.2.3
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-1.0.2.1
- aeson-compat-0.3.6
- aeson-pretty-0.8.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- appar-0.1.4
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.1.1
- attoparsec-0.13.1.0
- attoparsec-iso8601-1.0.0.0
- authenticate-1.3.3.2
- auto-update-0.1.4
- base-compat-0.9.3
- base-orphans-0.6
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- basic-prelude-0.6.1.1
- bifunctors-5.4.2
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- byteable-0.1.1
- byteorder-1.0.4
- bytes-0.15.3
- bytestring-builder-0.10.8.1.0
- cabal-doctest-1.0.1
- call-stack-0.1.0
- case-insensitive-1.2.0.9
- cereal-0.5.4.0
- chunked-data-0.3.0
- cipher-aes-0.2.11
- classy-prelude-1.2.0.1
- classy-prelude-conduit-1.2.0
- classy-prelude-yesod-1.2.0
- clientsession-0.9.1.2
- cmdargs-0.10.17
- comonad-5.0.1
- conduit-1.2.10
- conduit-combinators-1.1.1
- conduit-extra-1.1.15
- connection-0.2.8
- constraints-0.9.1
- contravariant-1.4
- cookie-0.4.2.1
- cprng-aes-0.6.1
- cron-0.5.0
- crypto-api-0.13.2
- crypto-cipher-types-0.0.9
- crypto-random-0.0.9
- cryptohash-0.11.9
- cryptohash-conduit-0.1.1
- cryptohash-cryptoapi-0.1.4
- cryptohash-md5-0.11.100.1
- cryptohash-sha1-0.11.100.1
- cryptohash-sha256-0.11.100.1
- cryptonite-0.23
- css-text-0.1.2.2
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- deepseq-generics-0.2.0.0
- distributive-0.5.2
- dlist-0.8.0.2
- dlist-instances-0.1.1.1
- easy-file-0.2.1
- ed25519-0.0.5.0
- email-validate-2.2.0
- entropy-0.3.7
- erf-2.0.0.0
- esqueleto-2.5.1
- exceptions-0.8.3
- fail-4.9.0.0
- fast-logger-2.4.10
- fb-1.1.1
- fsnotify-0.2.1
- file-embed-0.0.10
- flexible-defaults-0.0.1.2
- foundation-0.0.9
- free-4.12.4
- hackage-security-0.5.2.2
- hashable-1.2.6.0
- haskell-lexer-1.0.1
- hex-0.1.2
- hfsevents-0.1.6
- hinotify-0.3.9
- hjsmin-0.2.0.2
- hourglass-0.2.10
- hspec-2.4.3
- hspec-core-2.4.3
- hspec-discover-2.4.3
- hspec-expectations-0.8.2
- html-conduit-1.2.1.1
- http-api-data-0.3.7
- http-client-0.5.6.1
- http-client-tls-0.3.4.1
- http-conduit-2.2.3.1
- http-date-0.0.6.1
- http-reverse-proxy-0.4.4
- http-types-0.9.1
- http2-1.6.3
- integer-logarithms-1.0.1
- iproute-1.7.1
- kan-extensions-5.0.2
- keys-3.11
- language-javascript-0.6.0.9
- lifted-async-0.9.1.1
- lifted-base-0.2.3.10
- load-env-0.1.1
- log-domain-0.11
- math-functions-0.2.1.0
- memory-0.14.5
- mersenne-random-pure64-0.2.2.0
- microlens-0.4.8.0
- microlens-th-0.4.1.1
- mime-mail-0.4.13.1
- mime-mail-ses-0.3.2.3
- mime-types-0.1.0.7
- mmorph-1.0.9
- monad-control-1.0.1.0
- monad-logger-0.3.24
- monad-loops-0.4.3
- monad-unlift-0.2.0
- mono-traversable-1.0.2
- mono-traversable-instances-0.1.0.0
- mtl-2.2.1
- mtl-compat-0.2.1.3
- mutable-containers-0.3.3
- mwc-random-0.13.6.0
- nats-1.1.1
- network-2.6.3.1
- network-info-0.2.0.8
- network-uri-2.6.1.0
- nonce-1.0.2
- numbers-3000.2.0.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.13.2.0
- parsec-3.1.11
- path-pieces-0.2.1
- pem-0.2.2
- persistent-2.6.1
- persistent-postgresql-2.6.1
- persistent-sqlite-2.6.2
- persistent-template-2.5.2
- pointed-5
- postgresql-libpq-0.9.3.0
- postgresql-simple-0.5.2.1
- prelude-extras-0.4.0.3
- pretty-show-1.6.12
- primitive-0.6.2.0
- profunctors-5.2
- project-template-0.2.0
- psqueues-0.2.2.3
- quickcheck-io-0.1.4
- random-1.1
- random-fu-0.2.7.0
- random-shuffle-0.0.4
- random-source-0.3.0.6
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resource-pool-0.2.3.2
- resourcet-1.1.9
- rvar-0.2.0.3
- safe-0.3.14
- safe-exceptions-0.1.5.0
- safecopy-0.9.3.1
- say-0.1.0.0
- scientific-0.3.4.12
- securemem-0.1.9
- semigroupoids-5.2
- semigroups-0.18.3
- serversession-1.0.1
- serversession-backend-persistent-1.0.3
- serversession-frontend-yesod-1.0
- setenv-0.1.1.3
- shakespeare-2.0.13
- silently-1.2.5
- simple-sendfile-0.2.25
- skein-1.0.9.4
- socks-0.5.5
- split-0.2.3.1
- stateref-0.3
- stm-2.4.4.1
- stm-chans-3.0.0.4
- streaming-commons-0.1.17
- stringsearch-0.3.6.6
- syb-0.7
- system-filepath-0.4.13.4
- tagged-0.8.5
- tagsoup-0.14.1
- tagstream-conduit-0.5.5.3
- tar-0.5.0.3
- text-1.2.2.1
- tf-random-0.5
- th-extras-0.0.0.4
- th-lift-0.7.7
- th-lift-instances-0.1.11
- time-locale-compat-0.1.1.3
- tls-1.3.10
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- typed-process-0.1.0.0
- unix-compat-0.4.3.1
- unix-time-0.3.7
- unordered-containers-0.2.8.0
- uri-bytestring-0.2.3.1
- utf8-string-1.0.1.1
- uuid-1.3.13
- uuid-types-1.0.3
- vault-0.3.0.7
- vector-0.12.0.1
- vector-algorithms-0.7.0.1
- vector-instances-3.4
- vector-th-unbox-0.2.1.6
- void-0.7.2
- wai-3.2.1.1
- wai-app-static-3.1.6.1
- wai-extra-3.0.19.1
- wai-logger-2.3.0
- warp-3.2.11.2
- warp-tls-3.2.3
- word8-0.1.2
- x509-1.6.5
- x509-store-1.6.2
- x509-system-1.6.4
- x509-validation-1.6.5
- xml-conduit-1.4.0.4
- xml-types-0.3.6
- xss-sanitize-0.3.5.7
- yaml-0.8.22
- yesod-1.4.5
- yesod-auth-1.4.17
- yesod-auth-fb-1.8.1
- yesod-core-1.4.33
- yesod-fb-0.4.0
- yesod-form-1.4.11
- yesod-newsfeed-1.6
- yesod-persistent-1.4.2
- yesod-static-1.5.2
- yesod-test-1.5.5
- zlib-0.6.1.2
resolver: ghc-8.0.2
