# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

# TODO - these two should probably be under database, but I'm lazy
sslmode:     "_env:SSLMODE"
sslrootcert: "_env:SSLROOTCERT"

database:
  user:     "_env:PGUSER:fantasy"
  password: "_env:PGPASS:fantasy"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:fantasy"
  poolsize: "_env:PGPOOLSIZE:10"

copyright: © 2018 Fantasy Game Of Thrones
#analytics: UA-YOURCODE
